In [3]:
print('hello')

hello

In [6]:
import pandas as pd
import numpy as np

import sklearn

In [7]:
import pandas as pd

data = {
    "House": ["A", "B", "C"],
    "Price": [100000, 150000, 200000]
}

df = pd.DataFrame(data)

df

  House   Price
0     A  100000
1     B  150000
2     C  200000

In [8]:
# internet check
import pandas as pd

url = "https://raw.githubusercontent.com/ageron/handson-ml/master/datasets/housing/housing.csv"

df = pd.read_csv(url)

df.head()

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value,ocean_proximity
0,-122.23,37.88,41.0,880.0,129.0,322.0,126.0,8.3252,452600.0,NEAR BAY
1,-122.22,37.86,21.0,7099.0,1106.0,2401.0,1138.0,8.3014,358500.0,NEAR BAY
2,-122.24,37.85,52.0,1467.0,190.0,496.0,177.0,7.2574,352100.0,NEAR BAY
3,-122.25,37.85,52.0,1274.0,235.0,558.0,219.0,5.6431,341300.0,NEAR BAY
4,-122.25,37.85,52.0,1627.0,280.0,565.0,259.0,3.8462,342200.0,NEAR BAY

In [9]:
df.shape

(20640, 10)

In [10]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 20640 entries, 0 to 20639
Data columns (total 10 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   longitude           20640 non-null  float64
 1   latitude            20640 non-null  float64
 2   housing_median_age  20640 non-null  float64
 3   total_rooms         20640 non-null  float64
 4   total_bedrooms      20433 non-null  float64
 5   population          20640 non-null  float64
 6   households          20640 non-null  float64
 7   median_income       20640 non-null  float64
 8   median_house_value  20640 non-null  float64
 9   ocean_proximity     20640 non-null  str
dtypes: float64(9), str(1)
memory usage: 1.7 MB

In [11]:
df

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value,ocean_proximity
0,-122.23,37.88,41.0,880.0,129.0,322.0,126.0,8.3252,452600.0,NEAR BAY
1,-122.22,37.86,21.0,7099.0,1106.0,2401.0,1138.0,8.3014,358500.0,NEAR BAY
2,-122.24,37.85,52.0,1467.0,190.0,496.0,177.0,7.2574,352100.0,NEAR BAY
3,-122.25,37.85,52.0,1274.0,235.0,558.0,219.0,5.6431,341300.0,NEAR BAY
4,-122.25,37.85,52.0,1627.0,280.0,565.0,259.0,3.8462,342200.0,NEAR BAY
...,...,...,...,...,...,...,...,...,...,...
20635,-121.09,39.48,25.0,1665.0,374.0,845.0,330.0,1.5603,78100.0,INLAND
20636,-121.21,39.49,18.0,697.0,150.0,356.0,114.0,2.5568,77100.0,INLAND
20637,-121.22,39.43,17.0,2254.0,485.0,1007.0,433.0,1.7000,92300.0,INLAND
20638,-121.32,39.43,18.0,1860.0,409.0,741.0,349.0,1.8672,84700.0,INLAND
20639,-121.24,39.37,16.0,2785.0,616.0,1387.0,530.0,2.3886,89400.0,INLAND

In [12]:
df.columns

Index(['longitude', 'latitude', 'housing_median_age', 'total_rooms',
       'total_bedrooms', 'population', 'households', 'median_income',
       'median_house_value', 'ocean_proximity'],
      dtype='str')

In [13]:
df['total_bedrooms'].isnull().sum()

np.int64(207)

In [15]:
#df['median_house_value'].plot(kind='hist',bins=50)

In [16]:
#df.plot(kind='scatter',x = 'longitude', y = 'latitude')

In [17]:
df.head(10)

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value,ocean_proximity
0,-122.23,37.88,41.0,880.0,129.0,322.0,126.0,8.3252,452600.0,NEAR BAY
1,-122.22,37.86,21.0,7099.0,1106.0,2401.0,1138.0,8.3014,358500.0,NEAR BAY
2,-122.24,37.85,52.0,1467.0,190.0,496.0,177.0,7.2574,352100.0,NEAR BAY
3,-122.25,37.85,52.0,1274.0,235.0,558.0,219.0,5.6431,341300.0,NEAR BAY
4,-122.25,37.85,52.0,1627.0,280.0,565.0,259.0,3.8462,342200.0,NEAR BAY
5,-122.25,37.85,52.0,919.0,213.0,413.0,193.0,4.0368,269700.0,NEAR BAY
6,-122.25,37.84,52.0,2535.0,489.0,1094.0,514.0,3.6591,299200.0,NEAR BAY
7,-122.25,37.84,52.0,3104.0,687.0,1157.0,647.0,3.1200,241400.0,NEAR BAY
8,-122.26,37.84,42.0,2555.0,665.0,1206.0,595.0,2.0804,226700.0,NEAR BAY
9,-122.25,37.84,52.0,3549.0,707.0,1551.0,714.0,3.6912,261100.0,NEAR BAY

In [18]:
df.tail()

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value,ocean_proximity
20635,-121.09,39.48,25.0,1665.0,374.0,845.0,330.0,1.5603,78100.0,INLAND
20636,-121.21,39.49,18.0,697.0,150.0,356.0,114.0,2.5568,77100.0,INLAND
20637,-121.22,39.43,17.0,2254.0,485.0,1007.0,433.0,1.7000,92300.0,INLAND
20638,-121.32,39.43,18.0,1860.0,409.0,741.0,349.0,1.8672,84700.0,INLAND
20639,-121.24,39.37,16.0,2785.0,616.0,1387.0,530.0,2.3886,89400.0,INLAND

In [19]:
df.describe()

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
count,20640.000000,20640.000000,20640.000000,20640.000000,20433.000000,20640.000000,20640.000000,20640.000000,20640.000000
mean,-119.569704,35.631861,28.639486,2635.763081,537.870553,1425.476744,499.539680,3.870671,206855.816909
std,2.003532,2.135952,12.585558,2181.615252,421.385070,1132.462122,382.329753,1.899822,115395.615874
min,-124.350000,32.540000,1.000000,2.000000,1.000000,3.000000,1.000000,0.499900,14999.000000
25%,-121.800000,33.930000,18.000000,1447.750000,296.000000,787.000000,280.000000,2.563400,119600.000000
50%,-118.490000,34.260000,29.000000,2127.000000,435.000000,1166.000000,409.000000,3.534800,179700.000000
75%,-118.010000,37.710000,37.000000,3148.000000,647.000000,1725.000000,605.000000,4.743250,264725.000000
max,-114.310000,41.950000,52.000000,39320.000000,6445.000000,35682.000000,6082.000000,15.000100,500001.000000

In [20]:
df["total_bedrooms"]= df["total_bedrooms"].fillna(df["total_bedrooms"].median())

In [21]:
df.isnull().sum()

longitude             0
latitude              0
housing_median_age    0
total_rooms           0
total_bedrooms        0
population            0
households            0
median_income         0
median_house_value    0
ocean_proximity       0
dtype: int64

In [22]:
data = df.copy()

In [23]:
median_bedrooms = data["total_bedrooms"].median()

print("Median total bedrooms:", median_bedrooms)

Median total bedrooms: 435.0

In [24]:
data["total_bedrooms"] = data["total_bedrooms"].fillna(median_bedrooms)

In [25]:
data.isnull().sum()

longitude             0
latitude              0
housing_median_age    0
total_rooms           0
total_bedrooms        0
population            0
households            0
median_income         0
median_house_value    0
ocean_proximity       0
dtype: int64

In [26]:
data.columns

Index(['longitude', 'latitude', 'housing_median_age', 'total_rooms',
       'total_bedrooms', 'population', 'households', 'median_income',
       'median_house_value', 'ocean_proximity'],
      dtype='str')

In [27]:
numeric_data = data.select_dtypes(include="number")

correlation = numeric_data.corr()

correlation["median_house_value"].sort_values(ascending=False)

median_house_value    1.000000
median_income         0.688075
total_rooms           0.134153
housing_median_age    0.105623
households            0.065843
total_bedrooms        0.049457
population           -0.024650
longitude            -0.045967
latitude             -0.144160
Name: median_house_value, dtype: float64

In [30]:
#data.plot(kind="scatter",x="median_income", y="median_house_value",)

#plt.xlabel("Median Income")
#plt.ylabel("Median House Value")
#plt.title("Income vs House Value")
#plt.show()

In [31]:
numeric_data = data.select_dtypes(include="number")
correlation = numeric_data.corr()
correlation["median_house_value"].sort_values(ascending=False)

median_house_value    1.000000
median_income         0.688075
total_rooms           0.134153
housing_median_age    0.105623
households            0.065843
total_bedrooms        0.049457
population           -0.024650
longitude            -0.045967
latitude             -0.144160
Name: median_house_value, dtype: float64

In [32]:
X = data.drop("median_house_value", axis=1)
y = data["median_house_value"]

print("Features shape:", X.shape)
print("Target shape:", y.shape)

Features shape: (20640, 9)
Target shape: (20640,)

In [33]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

print("Training features:", X_train.shape)
print("Testing features:", X_test.shape)

print("Training target:", y_train.shape)
print("Testing target:", y_test.shape)

Training features: (16512, 9)
Testing features: (4128, 9)
Training target: (16512,)
Testing target: (4128,)

In [34]:
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import OneHotEncoder, StandardScaler
from sklearn.impute import SimpleImputer

# Identify numerical and categorical columns
numerical_features = X.select_dtypes(include=["int64", "float64"]).columns
categorical_features = X.select_dtypes(include=["object", "str"]).columns

print("Numerical features:")
print(list(numerical_features))

print("\nCategorical features:")
print(list(categorical_features))

Numerical features:
['longitude', 'latitude', 'housing_median_age', 'total_rooms', 'total_bedrooms', 'population', 'households', 'median_income']

Categorical features:
['ocean_proximity']

In [35]:
numerical_transformer = Pipeline(
    steps=[
        ("imputer", SimpleImputer(strategy="median")),
        ("scaler", StandardScaler())
    ]
)

categorical_transformer = Pipeline(
    steps=[
        ("imputer", SimpleImputer(strategy="most_frequent")),
        ("onehot", OneHotEncoder(handle_unknown="ignore"))
    ]
)

preprocessor = ColumnTransformer(
    transformers=[
        ("num", numerical_transformer, numerical_features),
        ("cat", categorical_transformer, categorical_features)
    ]
)

In [29]:
X_train_processed = preprocessor.fit_transform(X_train)

X_test_processed = preprocessor.transform(X_test)

print("Processed training data shape:", X_train_processed.shape)
print("Processed testing data shape:", X_test_processed.shape)

Processed training data shape: (16512, 13)
Processed testing data shape: (4128, 13)

In [36]:
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

# Create the full pipeline
linear_model = Pipeline(
    steps=[
        ("preprocessor", preprocessor),
        ("model", LinearRegression())
    ]
)

# Train the model
linear_model.fit(X_train, y_train)

print("Linear Regression model trained successfully!")

Linear Regression model trained successfully!

In [37]:
y_pred = linear_model.predict(X_test)

print(y_pred[:10])

[ 54055.44889898 124225.33893718 255489.37949166 268002.43156919
 262769.43481568 139606.3039556  290665.42391417 228264.87637529
 256506.78561005 407923.85843486]

In [38]:
mae = mean_absolute_error(y_test, y_pred)
mse = mean_squared_error(y_test, y_pred)
rmse = mse ** 0.5
r2 = r2_score(y_test, y_pred)

print("MAE:", mae)
print("RMSE:", rmse)
print("R² Score:", r2)

MAE: 50670.73824097191
RMSE: 70060.5218447352
R² Score: 0.6254240620553605

In [39]:
results = pd.DataFrame({
    "Actual Price": y_test.values[:10],
    "Predicted Price": y_pred[:10]
})

results

   Actual Price  Predicted Price
0       47700.0     54055.448899
1       45800.0    124225.338937
2      500001.0    255489.379492
3      218600.0    268002.431569
4      278000.0    262769.434816
5      158700.0    139606.303956
6      198200.0    290665.423914
7      157500.0    228264.876375
8      340000.0    256506.785610
9      446600.0    407923.858435

In [40]:
from sklearn.ensemble import RandomForestRegressor

forest_model = Pipeline(
    steps=[
        ("preprocessor", preprocessor),
        ("model", RandomForestRegressor(
            n_estimators=100,
            random_state=42,
            n_jobs=-1
        ))
    ]
)

forest_model.fit(X_train, y_train)

print("Random Forest model trained successfully!")

Random Forest model trained successfully!

In [41]:
forest_predictions = forest_model.predict(X_test)

print(forest_predictions[:10])

[ 51744.    71115.   461540.37 255273.   268425.   162987.   226880.02
 168563.   288998.05 484745.72]

In [42]:
forest_mae = mean_absolute_error(y_test, forest_predictions)
forest_mse = mean_squared_error(y_test, forest_predictions)
forest_rmse = forest_mse ** 0.5
forest_r2 = r2_score(y_test, forest_predictions)

print("Random Forest MAE:", forest_mae)
print("Random Forest RMSE:", forest_rmse)
print("Random Forest R²:", forest_r2)

Random Forest MAE: 31628.59239098837
Random Forest RMSE: 48941.954702938296
Random Forest R²: 0.8172085990009053

In [43]:
comparison = pd.DataFrame({
    "Model": [
        "Linear Regression",
        "Random Forest"
    ],
    "MAE": [
        mae,
        forest_mae
    ],
    "RMSE": [
        rmse,
        forest_rmse
    ],
    "R²": [
        r2,
        forest_r2
    ]
})

comparison

               Model           MAE          RMSE        R²
0  Linear Regression  50670.738241  70060.521845  0.625424
1      Random Forest  31628.592391  48941.954703  0.817209

In [44]:
from sklearn.model_selection import cross_val_score

cv_scores = cross_val_score(
    forest_model,
    X_train,
    y_train,
    scoring="r2",
    cv=5,
    n_jobs=-1
)

print("Cross-validation R² scores:")
print(cv_scores)

print("\nMean R²:", cv_scores.mean())

Cross-validation R² scores:
[0.82319847 0.814298   0.82041493 0.82000711 0.8139412 ]

Mean R²: 0.8183719392456205

In [45]:
data_engineered = data.copy()

data_engineered["rooms_per_household"] = (
    data_engineered["total_rooms"] /
    data_engineered["households"]
)

data_engineered["bedrooms_per_room"] = (
    data_engineered["total_bedrooms"] /
    data_engineered["total_rooms"]
)

data_engineered["population_per_household"] = (
    data_engineered["population"] /
    data_engineered["households"]
)

data_engineered.head()

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value,ocean_proximity,rooms_per_household,bedrooms_per_room,population_per_household
0,-122.23,37.88,41.0,880.0,129.0,322.0,126.0,8.3252,452600.0,NEAR BAY,6.984127,0.146591,2.555556
1,-122.22,37.86,21.0,7099.0,1106.0,2401.0,1138.0,8.3014,358500.0,NEAR BAY,6.238137,0.155797,2.109842
2,-122.24,37.85,52.0,1467.0,190.0,496.0,177.0,7.2574,352100.0,NEAR BAY,8.288136,0.129516,2.802260
3,-122.25,37.85,52.0,1274.0,235.0,558.0,219.0,5.6431,341300.0,NEAR BAY,5.817352,0.184458,2.547945
4,-122.25,37.85,52.0,1627.0,280.0,565.0,259.0,3.8462,342200.0,NEAR BAY,6.281853,0.172096,2.181467

In [46]:
data_engineered[
    [
        "rooms_per_household",
        "bedrooms_per_room",
        "population_per_household"
    ]
].describe()

       rooms_per_household  bedrooms_per_room  population_per_household
count         20640.000000       20640.000000              20640.000000
mean              5.429000           0.213794                  3.070655
std               2.474173           0.065248                 10.386050
min               0.846154           0.037151                  0.692308
25%               4.440716           0.175225                  2.429741
50%               5.229129           0.203159                  2.818116
75%               6.052381           0.240126                  3.282261
max             141.909091           2.824675               1243.333333

In [47]:
X = data_engineered.drop("median_house_value", axis=1)
y = data_engineered["median_house_value"]

In [48]:
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

In [49]:
numerical_features = X.select_dtypes(
    include=["int64", "float64"]
).columns

categorical_features = X.select_dtypes(
    include=["object", "str"]
).columns

print("Numerical features:", list(numerical_features))
print("Categorical features:", list(categorical_features))

Numerical features: ['longitude', 'latitude', 'housing_median_age', 'total_rooms', 'total_bedrooms', 'population', 'households', 'median_income', 'rooms_per_household', 'bedrooms_per_room', 'population_per_household']
Categorical features: ['ocean_proximity']

In [50]:
numerical_transformer = Pipeline(
    steps=[
        ("imputer", SimpleImputer(strategy="median")),
        ("scaler", StandardScaler())
    ]
)

categorical_transformer = Pipeline(
    steps=[
        ("imputer", SimpleImputer(strategy="most_frequent")),
        ("onehot", OneHotEncoder(handle_unknown="ignore"))
    ]
)

preprocessor = ColumnTransformer(
    transformers=[
        ("num", numerical_transformer, numerical_features),
        ("cat", categorical_transformer, categorical_features)
    ]
)

In [51]:
improved_forest = Pipeline(
    steps=[
        ("preprocessor", preprocessor),
        ("model", RandomForestRegressor(
            n_estimators=100,
            random_state=42,
            n_jobs=-1
        ))
    ]
)

improved_forest.fit(X_train, y_train)

print("Improved Random Forest trained!")

Improved Random Forest trained!

In [52]:
improved_predictions = improved_forest.predict(X_test)

improved_mae = mean_absolute_error(
    y_test,
    improved_predictions
)

improved_rmse = mean_squared_error(
    y_test,
    improved_predictions
) ** 0.5

improved_r2 = r2_score(
    y_test,
    improved_predictions
)

print("Improved MAE:", improved_mae)
print("Improved RMSE:", improved_rmse)
print("Improved R²:", improved_r2)

Improved MAE: 32339.097250484494
Improved RMSE: 50363.60343973001
Improved R²: 0.8064350448178869

In [53]:
# Go back to the original cleaned dataset
X_original = data.drop("median_house_value", axis=1)
y_original = data["median_house_value"]

X_train_original, X_test_original, y_train_original, y_test_original = train_test_split(
    X_original,
    y_original,
    test_size=0.2,
    random_state=42
)

print("Training data:", X_train_original.shape)
print("Testing data:", X_test_original.shape)

Training data: (16512, 9)
Testing data: (4128, 9)

In [54]:
numerical_features = X_original.select_dtypes(
    include=["int64", "float64"]
).columns

categorical_features = X_original.select_dtypes(
    include=["object", "str"]
).columns

numerical_transformer = Pipeline(
    steps=[
        ("imputer", SimpleImputer(strategy="median")),
        ("scaler", StandardScaler())
    ]
)

categorical_transformer = Pipeline(
    steps=[
        ("imputer", SimpleImputer(strategy="most_frequent")),
        ("onehot", OneHotEncoder(handle_unknown="ignore"))
    ]
)

final_preprocessor = ColumnTransformer(
    transformers=[
        ("num", numerical_transformer, numerical_features),
        ("cat", categorical_transformer, categorical_features)
    ]
)

In [55]:
final_model = Pipeline(
    steps=[
        ("preprocessor", final_preprocessor),
        ("model", RandomForestRegressor(
            n_estimators=100,
            random_state=42,
            n_jobs=-1
        ))
    ]
)

final_model.fit(
    X_train_original,
    y_train_original
)

print("FINAL MODEL TRAINED SUCCESSFULLY!")

FINAL MODEL TRAINED SUCCESSFULLY!

In [56]:
final_predictions = final_model.predict(X_test_original)

final_mae = mean_absolute_error(
    y_test_original,
    final_predictions
)

final_rmse = mean_squared_error(
    y_test_original,
    final_predictions
) ** 0.5

final_r2 = r2_score(
    y_test_original,
    final_predictions
)

print("Final MAE:", final_mae)
print("Final RMSE:", final_rmse)
print("Final R²:", final_r2)

Final MAE: 31628.59239098837
Final RMSE: 48941.954702938296
Final R²: 0.8172085990009053

In [63]:
import joblib

joblib.dump(final_model, "../models/house_price_model.pkl")

print("Model saved successfully!")

Model saved successfully!

In [64]:
loaded_model = joblib.load("../models/house_price_model.pkl")

print("Model loaded successfully!")

Model loaded successfully!

In [65]:
test_prediction = loaded_model.predict(
    X_test_original.iloc[:1]
)

print("Predicted house value:", test_prediction[0])
print("Actual house value:", y_test_original.iloc[0])

Predicted house value: 51744.0
Actual house value: 47700.0

In [66]:
import sys
import numpy
import sklearn
import joblib

print("Python:", sys.version)
print("Python location:", sys.executable)
print("NumPy:", numpy.__version__)
print("Scikit-learn:", sklearn.__version__)
print("Joblib:", joblib.__version__)

Python: 3.11.16 | packaged by Anaconda, Inc. | (main, Aug 27 2026, 14:36:16) [MSC v.1942 64 bit (AMD64)]
Python location: D:\Users\User\anaconda3\envs\houseapp\python.exe
NumPy: 2.4.6
Scikit-learn: 1.9.0
Joblib: 1.6.0

In [67]:
import sys
import numpy
import sklearn
import joblib

print("Python location:", sys.executable)
print("Python:", sys.version)
print("NumPy:", numpy.__version__)
print("Scikit-learn:", sklearn.__version__)
print("Joblib:", joblib.__version__)

Python location: D:\Users\User\anaconda3\envs\houseapp\python.exe
Python: 3.11.16 | packaged by Anaconda, Inc. | (main, Aug 27 2026, 14:36:16) [MSC v.1942 64 bit (AMD64)]
NumPy: 2.4.6
Scikit-learn: 1.9.0
Joblib: 1.6.0

In [68]:
import sys
import numpy
import sklearn
import joblib

print("Python:", sys.version)
print("Python location:", sys.executable)
print("NumPy:", numpy.__version__)
print("Scikit-learn:", sklearn.__version__)
print("Joblib:", joblib.__version__)

Python: 3.11.16 | packaged by Anaconda, Inc. | (main, Aug 27 2026, 14:36:16) [MSC v.1942 64 bit (AMD64)]
Python location: D:\Users\User\anaconda3\envs\houseapp\python.exe
NumPy: 2.4.6
Scikit-learn: 1.9.0
Joblib: 1.6.0

In [69]:
import os

print(os.getcwd())

C:\Users\User\Desktop\House price predicrion\notebooks

In [70]:
import os

print("Python is currently working in:")
print(os.getcwd())

print("\nFiles/folders in this location:")
print(os.listdir())

Python is currently working in:
C:\Users\User\Desktop\House price predicrion\notebooks

Files/folders in this location:
['.ipynb_checkpoints', 'house_price_prediction.ipynb']

In [71]:
import os

print(os.path.exists("models"))
print(os.path.abspath("models"))

False
C:\Users\User\Desktop\House price predicrion\notebooks\models